name: Docker Nightly Production

on:
  push:
    branches:
      - armv7

concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    name: "Backend Server Tests"
    uses: ./.github/workflows/partial-backend.yml

  frontend-tests:
    name: "Frontend and End-to-End Tests"
    uses: ./.github/workflows/partial-frontend.yml

  build-release:
    permissions:
      contents: read
      packages: write
    name: Build Tagged Release
    uses: ./.github/workflows/partial-builder.yml
    needs:
      - frontend-tests
      - backend-tests
    with:
      tag: nightly
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}