name: Docker Build Production

on:
  release:
    types: [published]

jobs:
  backend-tests:
    name: "Backend Server Tests"
    uses: ./.github/workflows/partial-backend.yml

  frontend-tests:
    name: "Frontend and End-to-End Tests"
    uses: ./.github/workflows/partial-frontend.yml

  build-release:
    permissions:
      contents: read
      packages: write
    name: Build Tagged Release
    uses: ./.github/workflows/partial-builder.yml
    needs:
      - backend-tests
      - frontend-tests
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}